import java.util.Scanner;

public class Main {
  public static void main(String[] args) {

    char gameGrid[][] = new char[3][3];
    char playerX = 'X';
    char playerO = 'O';

    boolean gridFull = false;

    Scanner scanner = new Scanner(System.in);

    System.out.println("Welcome to Tic Tac Toe!");
    makeGameGrid(gameGrid);
    printGameGrid(gameGrid);

    while (!gridFull) {
      if (!checkWin(gameGrid)) {
        System.out.println("PlayerX, please enter your X move");
        System.out.println("Row number(1-3): ");
        int row = scanner.nextInt() - 1;
        System.out.println("Column number(1-3): ");
        int column = scanner.nextInt() - 1;
        gameGrid[row][column] = playerX;
        printGameGrid(gameGrid);

        if (checkWin(gameGrid)) {
          System.out.println("PlayerX wins!");
          break;
        }

        if (isGridFull(gameGrid)) {
          gridFull = true;
          System.out.println("It's a draw!");
          break;
        }

        System.out.println("Player0, please enter your 0 move");
        System.out.println("Row number(1-3): ");
        row = scanner.nextInt() - 1;
        System.out.println("Column number(1-3): ");
        column = scanner.nextInt() - 1;
        gameGrid[row][column] = playerO;
        printGameGrid(gameGrid);

        if (checkWin(gameGrid)) {
          System.out.println("PlayerO wins!");
        }

        if (isGridFull(gameGrid)) {
          gridFull = true;
          System.out.println("It's a draw!");
          break;
        }
      }
    }
  }

  public static void makeGameGrid(char[][] gameGrid) {
    for (int i = 0; i < 3; i++) {
      for (int j = 0; j < 3; j++) {
        gameGrid[i][j] = '-';
      }
    }
  }

  public static void printGameGrid(char[][] gameGrid) {
    System.out.println(" -------------");
    for (int i = 0; i < 3; i++) {
      System.out.print(" | ");
      for (int j = 0; j < 3; j++) {
        System.out.print(gameGrid[i][j]);
        System.out.print(" | ");
      }
      System.out.println();
      System.out.println(" -------------");
    }
  }

  public static boolean checkWin(char[][] gameGrid) {
    for (int i = 0; i < 3; i++) {
      if (gameGrid[i][0] == gameGrid[i][1] && gameGrid[i][1] == gameGrid[i][2] && gameGrid[i][0] != '-') {
        return true;
      }
    }

    for (int j = 0; j < 3; j++) {
      if (gameGrid[0][j] == gameGrid[1][j] && gameGrid[1][j] == gameGrid[2][j] && gameGrid[0][j] != '-') {
        return true;
      }
    }

    if (gameGrid[0][0] == gameGrid[1][1] && gameGrid[1][1] == gameGrid[2][2] && gameGrid[0][0] != '-') {
      return true;
    }

    if (gameGrid[0][2] == gameGrid[1][1] && gameGrid[1][1] == gameGrid[2][0] && gameGrid[0][2] != '-') {
      return true;
    }
    return false;
  }

  public static boolean isGridFull(char[][] gameGrid) {
    for (int i = 0; i < 3; i++) {
      for (int j = 0; j < 3; j++) {
        if (gameGrid[i][j] == '-') {
          return false;
        }
      }
    }
    return true;
  }
}
